name: isort
on: pull_request
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: files
        uses: tj-actions/changed-files@v35.9.2
        with:
          files: |
              cvat-sdk/**/*.py
              cvat-cli/**/*.py
              tests/python/**/*.py
              cvat/apps/quality_control/**/*.py
          dir_names: true

      - name: Run checks
        run: |
          # If different modules use different isort configs,
          # we need to run isort for each python component group separately.
          # Otherwise, they all will use the same config.

          UPDATED_DIRS="${{steps.files.outputs.all_changed_files}}"

          if [[ ! -z $UPDATED_DIRS ]]; then
            sudo apt-get --no-install-recommends install -y build-essential curl python3-dev python3-pip python3-venv
            python3 -m venv .env
            . .env/bin/activate
            pip install -U pip wheel setuptools
            pip install $(egrep "isort.*" ./cvat-cli/requirements/development.txt)
            mkdir -p isort_report

            echo "isort version: $(isort --version-number)"
            echo "The dirs will be checked: $UPDATED_DIRS"
            EXIT_CODE=0
            for DIR in $UPDATED_DIRS; do
              isort --check $DIR >> ./isort_report/isort_checks.txt || EXIT_CODE=$(($? | $EXIT_CODE)) || true
            done
            deactivate
            exit $EXIT_CODE
          else
            echo "No files with the \"py\" extension found"
          fi

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v3.1.1
        with:
          name: isort_report
          path: isort_report
