name: StyleLint
on: pull_request
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: '16.x'
      - id: files
        uses: tj-actions/changed-files@v35.9.2
        with:
          files: |
              **/*.css
              **/*.scss

      - name: Run checks
        run: |
          CHANGED_FILES="${{steps.files.outputs.all_changed_files}}"

          if [[ ! -z $CHANGED_FILES ]]; then
            yarn install --frozen-lockfile
            mkdir -p stylelint_report

            echo "StyleLint version: "$(npx stylelint --version)
            echo "The files will be checked: "$(echo $CHANGED_FILES)
            npx stylelint --formatter json --output-file ./stylelint_report/stylelint_report.json $CHANGED_FILES || EXIT_CODE=$(echo $?) || true
            pip install json2html
            python ./tests/json_to_html.py ./stylelint_report/stylelint_report.json
            exit $EXIT_CODE
          else
            echo "No files with the \"css|scss\" extension found"
          fi

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v3.1.1
        with:
          name: stylelint_report
          path: stylelint_report
